Snorktracker: tracker/Debug.h File Reference
Debug.h File Reference
Functions
void myDebugInfo (String info, bool isWebServer, bool newline)
void MyDbg (String info, bool fromWebServer=false, bool newline=true)
void myDelayLoop ()
void myDelay (long millisDelay)
Detailed Description
Helper functions for a MyDbg macro which can show all the debug information on the console page and a helper function for a delay function who can update some webbrowser information in the background.
Definition in file Debug.h.
Function Documentation
void MyDbg (String info, bool fromWebServer = false, bool newline = true)
Short version of myDebugInfo. fromWebServer prevents recursive calls when from WebServer
Definition at line 31 of file Debug.h.
References myDebugInfo().
Referenced by MyGsmPower::begin(), MyDeepSleep::begin(), MySmsCmd::begin(), MyGsmGps::begin(), MyWebServer::begin(), MyMqtt::begin(), MySmsCmd::checkSms(), MyGsmGps::deleteSMS(), MyGsmGps::enableGps(), MyGsmGps::getGps(), MyGsmGps::getSMS(), MyWebServer::handleLoadConsoleInfo(), MyWebServer::handleLoadSettingsInfo(), MyWebServer::handleNotFound(), MyWebServer::handleSaveSettings(), MyOptions::load(), MyWebServer::loadRestart(), MyMqtt::mqttCallback(), MyGsmPower::off(), MyGsmPower::on(), readFromSpiffs(), readVoltage(), MyMqtt::reconnect(), MyOptions::save(), MyGsmGps::sendAT(), MyMqtt::sendData(), MyGsmGps::sendSMS(), setup(), SetupOTA(), MyDeepSleep::sleep(), MyGsmGps::sleepMode2(), and MyGsmGps::stop().
 {
    myDebugInfo(info, fromWebServer, newline);
 }
void myDebugInfo (String info, bool fromWebserver, bool newline)
This function has to be overwritten to implement the handle of debug informations.
Overwritten Debug Function It logs all the debug calls to the console string-list And call a refresh of the webserver for not blocking the system.
Definition at line 72 of file tracker.ino.
References StringList::addTail(), MyWebServer::handleClient(), MyData::logInfos, myWebServer, and StringList::removeTail().
Referenced by MyDbg().
 {
    static bool lastNewLine = true;
    if (newline || lastNewLine != newline) {
       String secs = String(millis() / 1000) + ": ";
       myData.logInfos.addTail(secs + info);
       if (!lastNewLine) {
          Serial.println("");
       }
       Serial.println(secs + info);
    } else {
       String tmp = myData.logInfos.removeTail();
       myData.logInfos.addTail(tmp + info);
       Serial.print(info);
    }
    lastNewLine = newline;
    if (!fromWebserver) {
       myWebServer.handleClient();
       myWebServer.handleClient();
       myWebServer.handleClient();
    }
 }
void myDelay (long millisDelay)
Replacement with background calls when we have to wait. Replace the delay function.
Definition at line 41 of file Debug.h.
References myDelayLoop().
Referenced by MyGsmGps::begin(), MyWebServer::begin(), MyWebServer::loadRestart(), MyGsmPower::on(), and MyMqtt::reconnect().
 {
    long m = millis();
    while (millis() - m < millisDelay) {
       myDelayLoop();
       yield();
       delay(1);
    }
 }
void myDelayLoop ()
This function has to be overwritten to implement background delay calls.
Overwritten delay loop for refreshing the webserver on waiting processes.
Definition at line 99 of file tracker.ino.
References MyWebServer::handleClient(), and myWebServer.
Referenced by myDelay().
 {
    myWebServer.handleClient();
    myWebServer.handleClient();
    myWebServer.handleClient();
    delay(0);
    yield();
 }