Snorktracker: MyWebServer Class Reference
MyWebServer Class Reference
#include <WebServer.h>
Public Member Functions
MyWebServer (MyOptions &options, MyData &data)
bool begin ()
void handleClient ()
Static Public Member Functions
static void handleRoot ()
static void loadMain ()
static void handleLoadMainInfo ()
static void loadFirmwareUpdate ()
static void loadSettings ()
static void handleLoadSettingsInfo ()
static void handleSaveSettings ()
static void handleLoadInfoInfo ()
static void loadConsole ()
static void handleLoadConsoleInfo ()
static void loadRestart ()
static void handleLoadRestartInfo ()
static void handleNotFound ()
static void handleWebRequests ()
Data Fields
bool isWebServerActive
Is the webserver currently active.
Static Public Attributes
static ESP8266WebServer server
Webserver helper class.
static IPAddress ip
Soft AP ip Address.
static DNSServer dnsServer
Dns server.
static MyOptions * myOptions = NULL
Reference to the options.
static MyData * myData = NULL
Reference to the data.
Static Protected Member Functions
static bool loadFromSpiffs (String path)
static String TextToXml (String data)
static void AddTableBegin (String &info)
static void AddTableTr (String &info)
static void AddTableTr (String &info, String name, String value)
static void AddTableEnd (String &info)
static bool GetOption (String id, String &option)
static bool GetOption (String id, long &option)
static bool GetOption (String id, double &option)
static bool GetOption (String id, bool &option)
static void AddBr (String &info)
static void AddOption (String &info, String id, String name, bool value, bool addBr=true)
static void AddOption (String &info, String id, String name, String value, bool addBr=true, bool isPassword=false)
Detailed Description
My Webserver interface. Works together with .html, .css and .js files from the SPIFFS. Works mostly with static functions because of the server callback functions.
Definition at line 35 of file WebServer.h.
Constructor & Destructor Documentation
MyWebServer::MyWebServer (MyOptions & options, MyData & data)
Constructor/Destructor
Definition at line 96 of file WebServer.h.
References myData, and myOptions.
    : isWebServerActive(false)
 {
    myOptions = &options;
    myData    = &data;
 }
Member Function Documentation
void MyWebServer::AddBr (String & info) static protected
Add a HTML br element.
Definition at line 260 of file WebServer.h.
Referenced by handleLoadSettingsInfo().
 {
    info += "<br />";
 }
void MyWebServer::AddOption (String & info, String id, String name, bool value, bool addBr = true) static protected
Add one bool input option field to the HTML source.
Definition at line 280 of file WebServer.h.
References TextToXml().
Referenced by handleLoadSettingsInfo().
 {
    info += "<input style='width:auto;' id='" + id + "' name='" + id + "' type='checkbox' " +
            (String) (value ? " checked" : "") + "><b>" + TextToXml(name) + "</b>";
    if (addBr) {
       info += "<br />";
    }
 }
void MyWebServer::AddOption (String & info, String id, String name, String value, bool addBr = true, bool isPassword = false) static protected
Add one string input option field to the HTML source.
Definition at line 266 of file WebServer.h.
References TextToXml().
 {
    info += "<b>" + TextToXml(name) + "</b>";
    info += "<input id='" + id + "' name='" + id + "' ";
    if (isPassword) {
       info += " type='password' ";
    }
    info += "placeholder='' value='" + TextToXml(value) + "'>";
    if (addBr) {
       info += "<br />";
    }
 }
void MyWebServer::AddTableBegin (String & info) static protected
Helper function to start a HTML table.
Definition at line 182 of file WebServer.h.
Referenced by handleLoadInfoInfo(), and handleLoadMainInfo().
 {
    info += "<table style='width:100%'>";
 }
void MyWebServer::AddTableEnd (String & info) static protected
Helper function to add one HTML table end element.
Definition at line 205 of file WebServer.h.
Referenced by handleLoadInfoInfo(), and handleLoadMainInfo().
 {
    info += "</table>";
 }
void MyWebServer::AddTableTr (String & info) static protected
Helper function to write one HTML row with no data.
Definition at line 188 of file WebServer.h.
Referenced by handleLoadInfoInfo(), and handleLoadMainInfo().
 {
    info += "<tr><th></th><td>&nbsp;</td></tr>";
 }
void MyWebServer::AddTableTr (String & info, String name, String value) static protected
Helper function to add one HTML table row line with data.
Definition at line 194 of file WebServer.h.
References TextToXml().
 {
    if (value != "") {
       info += "<tr>";
       info += "<th>" + TextToXml(name)  + "</th>";
       info += "<td>" + TextToXml(value) + "</td>";
       info += "</tr>";
    }
 }
bool MyWebServer::begin ()
Starts the Webserver in station and/or ap mode and sets all the callback functions for the specific urls.
Definition at line 110 of file WebServer.h.
References dnsServer, handleLoadConsoleInfo(), handleLoadInfoInfo(), handleLoadMainInfo(), handleLoadRestartInfo(), handleLoadSettingsInfo(), handleRoot(), handleSaveSettings(), handleWebRequests(), ip, isWebServerActive, loadConsole(), loadFirmwareUpdate(), loadMain(), loadRestart(), loadSettings(), myData, MyDbg(), myDelay(), myOptions, server, MyData::softAPIP, MyData::softAPmacAddress, MyData::stationIP, MyOptions::wlanAP, and MyOptions::wlanPassword.
Referenced by setup().
 {
    if (!myOptions || !myData) {
       return false;
    }
    MyDbg("MyWebServer::begin");
    WiFi.mode(WIFI_AP_STA);
    WiFi.softAP("ESP8266AP", "");
    WiFi.softAPConfig(ip, ip, IPAddress(255, 255, 255, 0));
    dnsServer.setErrorReplyCode(DNSReplyCode::NoError);
    dnsServer.start(53, "*", ip);
    myData->softAPIP         = WiFi.softAPIP().toString();
    myData->softAPmacAddress =  WiFi.softAPmacAddress();
    MyDbg("SoftAPIP address: " + myData->softAPIP, true);
    MyDbg("SoftAPIP mac address: " + myData->softAPmacAddress, true);
    WiFi.begin(myOptions->wlanAP.c_str(), myOptions->wlanPassword.c_str());
    for (int i = 0; i < 20 && WiFi.status() != WL_CONNECTED; i++) { // 10 Sec versuchen
       MyDbg(".", true, false);
       myDelay(500);
    }
    if (WiFi.status() == WL_CONNECTED) {
       myData->stationIP = WiFi.localIP().toString();
       MyDbg("Connected to "        + myOptions->wlanAP, true);
       MyDbg("Station IP address: " + myData->stationIP, true);
    } else { // switch to AP Mode only
       MyDbg((String) "No connection to " + myOptions->wlanAP, true);
       WiFi.disconnect();
       WiFi.mode(WIFI_AP);
    }
    server.on("/",                    handleRoot);
    server.on("/Main.html",           loadMain);
    server.on("/MainInfo",            handleLoadMainInfo);
    server.on("/FirmwareUpdate.html", loadFirmwareUpdate);
    server.on("/Settings.html",       loadSettings);
    server.on("/SettingsInfo",        handleLoadSettingsInfo);
    server.on("/SaveSettings",        handleSaveSettings);
    server.on("/InfoInfo",            handleLoadInfoInfo);
    server.on("/Console.html",        loadConsole);
    server.on("/ConsoleInfo",         handleLoadConsoleInfo);
    server.on("/Restart.html",        loadRestart);
    server.on("/RestartInfo",         handleLoadRestartInfo);
    server.onNotFound(handleWebRequests);
    server.begin();
    MyDbg("Server listening", true);
    isWebServerActive = true;
    return true;
 }
bool MyWebServer::GetOption (String id, String & option) static protected
Reads one string option from the url args.
Definition at line 211 of file WebServer.h.
References server.
Referenced by handleSaveSettings().
 {
    if (server.hasArg(id)) {
       option = server.arg(id);
       return true;
    }
    return false;
 }
bool MyWebServer::GetOption (String id, long & option) static protected
Reads one long option from the URL args.
Definition at line 221 of file WebServer.h.
References server.
 {
    String opt = server.arg(id);
    if (opt != "") {
       option = atoi(opt.c_str());
       return true;
    }
    return false;
 }
bool MyWebServer::GetOption (String id, double & option) static protected
Reads one double option from the URL args.
Definition at line 233 of file WebServer.h.
References server.
 {
    String opt = server.arg(id);
    if (opt != "") {
       option = atof(opt.c_str());
       return true;
    }
    return false;
 }
bool MyWebServer::GetOption (String id, bool & option) static protected
Reads one bool option from the URL args.
Definition at line 245 of file WebServer.h.
References server.
 {
    String opt = server.arg(id);
    option = false;
    if (opt != "") {
       if (opt == "on") {
          option = true;
       }
       return true;
    }
    return false;
 }
void MyWebServer::handleClient ()
Handle the http requests.
Definition at line 164 of file WebServer.h.
References dnsServer, isWebServerActive, and server.
Referenced by loop(), myDebugInfo(), and myDelayLoop().
 {
    if (isWebServerActive) {
       server.handleClient();
       dnsServer.processNextRequest();
    }
 }
void MyWebServer::handleLoadConsoleInfo () static
Handle the Console ajax calls to get AT commands and show the result of the calls or debug informations.
Definition at line 592 of file WebServer.h.
References StringList::addTail(), MyData::consoleCmds, StringList::count(), StringList::getAt(), MyData::logInfos, myData, MyDbg(), myOptions, server, and TextToXml().
Referenced by begin().
 {
    if (!myOptions || !myData) {
       return;
    }
    String sendData;
    String cmd      = server.arg("c1");
    String startIdx = server.arg("c2");
    if (server.hasArg("c1")) {
       MyDbg(cmd, true);
       myData->consoleCmds.addTail(cmd);
    }
    sendData =
       "<r>"
          "<i>" + String(myData->logInfos.count()) + "</i>"
          "<j>1</j>"
          "<l>";
             for (int i = atoi(startIdx.c_str()); i < myData->logInfos.count(); i++) {
                sendData += TextToXml(myData->logInfos.getAt(i));
                sendData += '\n';
             }
    sendData +=
          "</l>"
       "</r>";
    server.send(200,"text/xml", sendData.c_str());
 }
void MyWebServer::handleLoadInfoInfo () static
Load the detail info part via ajax call.
Definition at line 514 of file WebServer.h.
References AddTableBegin(), AddTableEnd(), AddTableTr(), MyData::altitude, MyData::batteryLevel, MyData::batteryVolt, MyData::cop, MyData::course, MyData::gpsDate, MyData::gpsTime, MyData::imei, MyData::isMoving, MyData::isOtaActive, MyData::kmph, MyData::latitude, MyData::longitude, MyData::modemInfo, MyData::modemIP, MyData::movingDistance, myData, myOptions, MyData::satellites, server, MyData::signalQuality, MyData::softAPIP, MyData::softAPmacAddress, MyData::stationIP, MyData::status, WifiGetRssiAsQuality(), and MyOptions::wlanAP.
Referenced by begin().
 {
    if (!myOptions || !myData) {
       return;
    }
    String info;
    String ssidRssi = (String) myOptions->wlanAP + " (" + WifiGetRssiAsQuality(WiFi.RSSI()) + "%)";
    AddTableBegin(info);
    if (myData->status != "") {
       AddTableTr(info, "Status",               myData->status);
       AddTableTr(info);
    }
    if (myData->isOtaActive) {
       AddTableTr(info, "OTA",                  "Active");
       AddTableTr(info);
    }
    if (ssidRssi != "" || myData->softAPIP || myData->softAPmacAddress != "" || myData->stationIP != "") {
       AddTableTr(info, "AP1 SSID (RSSI)",      ssidRssi);
       AddTableTr(info, "AP IP",                myData->softAPIP);
       AddTableTr(info, "Locale IP",            myData->stationIP);
       AddTableTr(info, "MAC Address",          myData->softAPmacAddress);
       AddTableTr(info);
    }
    if (myData->modemInfo     != "" || myData->modemIP != ""      || myData->imei        != "" || myData->cop != "" ||
        myData->signalQuality != "" || myData->batteryLevel != "" || myData->batteryVolt != "") {
       AddTableTr(info, "Modem Info",           myData->modemInfo);
       AddTableTr(info, "Modem IP",             myData->modemIP);
       AddTableTr(info, "IMEI",                 myData->imei);
       AddTableTr(info, "COP",                  myData->cop);
       AddTableTr(info, "Signal Quality",       myData->signalQuality);
       AddTableTr(info, "Battery Level",        myData->batteryLevel);
       AddTableTr(info, "Battery Volt",         myData->batteryVolt);
       AddTableTr(info);
    }
    if (myData->longitude  != "" || myData->latitude != "" || myData->altitude != "" || myData->kmph    != "" ||
        myData->satellites != "" || myData->course   != "" || myData->gpsDate  != "" || myData->gpsTime != "") {
       AddTableTr(info, "Longitude",            myData->longitude);
       AddTableTr(info, "Latitude",             myData->latitude);
       AddTableTr(info, "Altitude",             myData->altitude);
       AddTableTr(info, "Km/h",                 myData->kmph);
       AddTableTr(info, "Satellite",            myData->satellites);
       AddTableTr(info, "Course",               myData->course);
       AddTableTr(info, "GPS Datum",            myData->gpsDate);
       AddTableTr(info, "GPS Time",             myData->gpsTime);
       AddTableTr(info);
    }
    if (myData->isMoving || myData->movingDistance != 0.0) {
       AddTableTr(info, "Moving",               myData->isMoving ? "Yes" : "No");
       AddTableTr(info, "Distance (m)",         String(myData->movingDistance, 2));
       AddTableTr(info);
    }
    AddTableTr(info, "ESP Chip ID",            String(ESP.getChipId()));
    AddTableTr(info, "Flash Chip ID",          String(ESP.getFlashChipId()));
    AddTableTr(info, "Real Flash Memory",      String(ESP.getFlashChipRealSize() / 1024) + " kB");
    AddTableTr(info, "Total Flash Memory",     String(ESP.getFlashChipSize()     / 1024) + " kB");
    AddTableTr(info, "Used Flash Memory",      String(ESP.getSketchSize()        / 1024) + " kB");
    AddTableTr(info, "Free Sketch Memory",     String(ESP.getFreeSketchSpace()   / 1024) + " kB");
    AddTableTr(info, "Free Heap Memory",       String(ESP.getFreeHeap()          / 1024) + " kB");
    AddTableEnd(info);
    server.send(200,"text/html", info);
 }
void MyWebServer::handleLoadMainInfo () static
Handle the ajax call of the Main.html detail information.
Definition at line 340 of file WebServer.h.
References AddTableBegin(), AddTableEnd(), AddTableTr(), MyData::altitude, MyOptions::gsmPower, MyData::humidity, MyData::latitude, MyData::longitude, MyData::modemInfo, myData, myOptions, MyData::satellites, MyOptions::save(), MyData::secondsToDeepSleep, server, MyData::status, MyData::temperature, and MyData::voltage.
Referenced by begin().
 {
    if (!myOptions || !myData) {
       return;
    }
    String info;
    String onOff = server.arg("o");
    if (onOff == "1") {
       myOptions->gsmPower = !myOptions->gsmPower;
       myOptions->save();
    }
    AddTableBegin(info);
    if (myData->status != "") {
       AddTableTr(info, "Status", myData->status);
    }
    AddTableTr(info, "Battery",     String(myData->voltage,     1) + " V");
    AddTableTr(info, "Temperature", String(myData->temperature, 1) + " C");
    AddTableTr(info, "Humidity",    String(myData->humidity,    1) + " %");
    AddTableTr(info, "Pressure",    String(myData->temperature, 1) + " hPa");
    if (myData->status != "") {
       AddTableTr(info, "Modem Info", myData->modemInfo);
       AddTableTr(info, "Longitude",  myData->longitude);
       AddTableTr(info, "Latitude",   myData->latitude);
       AddTableTr(info, "Altitude",   myData->altitude);
       AddTableTr(info, "Satellites", myData->satellites);
    }
    if (myData->secondsToDeepSleep >= 0) {
       AddTableTr(info, "Power saving in ", String(myData->secondsToDeepSleep) + " Seconds");
    }
    AddTableEnd(info);
    info +=
       "<table style='width:100%'>"
          "<tr>"
             "<td style='width:100%'>"
                "<div style='text-align:center;font-weight:bold;font-size:62px'>"
                   + (String) (myOptions->gsmPower ? "ON" : "OFF") +
                "</div>"
             "</td>"
          "</tr>"
       "</table>";
    server.send(200,"text/html", info);
 }
void MyWebServer::handleLoadRestartInfo () static
Handle the restart ajax call of the restart reason.
Definition at line 636 of file WebServer.h.
References myData, myOptions, MyData::restartInfo, and server.
Referenced by begin().
 {
    if (!myOptions || !myData) {
       return;
    }
    server.send(200,"text/html", myData->restartInfo);
    myData->restartInfo = "";
 }
void MyWebServer::handleLoadSettingsInfo () static
Sends the ajax settings detail information to the client.
Definition at line 416 of file WebServer.h.
References AddBr(), AddOption(), MyOptions::bme280CheckIntervalSec, MyOptions::deepSleepTimeSec, MyOptions::gprsAP, MyOptions::gpsCheckIntervalSec, MyOptions::isDebugActive, MyOptions::isDeepSleepEnabled, MyOptions::isGpsEnabled, MyOptions::isGsmEnabled, MyOptions::isMqttEnabled, MyOptions::mqttName, MyOptions::mqttPassword, MyOptions::mqttPort, MyOptions::mqttReconnectIntervalSec, MyOptions::mqttSendOnMoveEverySec, MyOptions::mqttSendOnNonMoveEverySec, MyOptions::mqttServer, MyOptions::mqttUser, myData, MyDbg(), myOptions, MyOptions::phoneNumber, MyOptions::powerCheckIntervalSec, MyOptions::powerSaveModeVoltage, server, MyOptions::smsCheckIntervalSec, MyOptions::wakeTimeSec, MyOptions::wlanAP, and MyOptions::wlanPassword.
Referenced by begin().
 {
    if (!myOptions || !myData) {
       return;
    }
    String info;
    MyDbg("LoadSettings", true);
    AddOption(info, "wlanAP",                 "WLAN SSID",                         myOptions->wlanAP);
    AddOption(info, "wlanPassword",           "WLAN Password",                     myOptions->wlanPassword, true, true);
    AddOption(info, "gprsAP",                 "GPRS AP",                           myOptions->gprsAP);
    AddOption(info, "isDebugActive",          "Debug Active",                      myOptions->isDebugActive);
    AddOption(info, "bme280CheckIntervalSec", "Temperature check every (Seconds)", String(myOptions->bme280CheckIntervalSec));
    AddOption(info, "isGsmEnabled",           "GSM Enabled",                       myOptions->isGsmEnabled);
    AddOption(info, "isGpsEnabled",           "GPS Enabled",                       myOptions->isGpsEnabled);
    AddOption(info, "gpsCheckIntervalSec",    "GPS check every (Seconds)",         String(myOptions->gpsCheckIntervalSec));
    AddOption(info, "phoneNumber",            "Information send to",               myOptions->phoneNumber);
    AddOption(info, "smsCheckIntervalSec",    "SMS check every (Seconds)",         String(myOptions->smsCheckIntervalSec));
    {
       HtmlTag fieldset(info, "fieldset");
       {
          HtmlTag legend(info, "legend");
          AddOption(info, "isDeepSleepEnabled", "Power saving mode active", myOptions->isDeepSleepEnabled, false);
       }
       AddOption(info, "powerSaveModeVoltage",  "Power saving mode under (Volt)", String(myOptions->powerSaveModeVoltage, 1));
       AddOption(info, "powerCheckIntervalSec", "Check power every (Seconds)",    String(myOptions->powerCheckIntervalSec));
       AddOption(info, "wakeTimeSec",          "Active time (Seconds)",           String(myOptions->wakeTimeSec));
       AddOption(info, "deepSleepTimeSec",     "DeepSleep time (Seconds)",        String(myOptions->deepSleepTimeSec));
    }
    AddBr(info);
    {
       HtmlTag fieldset(info, "fieldset");
       {
          HtmlTag legend(info, "legend");
          AddOption(info, "isMqttEnabled", "MQTT Active", myOptions->isMqttEnabled, false);
       }
       AddOption(info, "mqttName",                  "MQTT Name",                             myOptions->mqttName);
       AddOption(info, "mqttServer",                "MQTT Server",                           myOptions->mqttServer);
       AddOption(info, "mqttPort",                  "MQTT Port",                             String(myOptions->mqttPort));
       AddOption(info, "mqttUser",                  "MQTT User",                             myOptions->mqttUser);
       AddOption(info, "mqttPassword",              "MQTT Password",                         myOptions->mqttPassword, true, true);
       AddOption(info, "mqttReconnectIntervalSec",  "MQTT Reconnect every (Seconds)",        String(myOptions->mqttReconnectIntervalSec));
       AddOption(info, "mqttSendOnMoveEverySec",    "MQTT Send on moving every (Seconds)",   String(myOptions->mqttSendOnMoveEverySec));
       AddOption(info, "mqttSendOnNonMoveEverySec", "MQTT Send on standing every (Seconds)", String(myOptions->mqttSendOnNonMoveEverySec), false);
    }
    server.send(200,"text/html", info);
 }
void MyWebServer::handleNotFound () static
Handle if the url could not be found.
Definition at line 647 of file WebServer.h.
References myData, MyDbg(), myOptions, and server.
Referenced by handleWebRequests(), loadConsole(), loadFirmwareUpdate(), loadMain(), loadRestart(), and loadSettings().
 {
    if (!myOptions || !myData) {
       return;
    }
    String message = "File Not Found\n\n";
    message += "URI: ";
    message += server.uri();
    message += "\nMethod: ";
    message += (server.method() == HTTP_GET)?"GET":"POST";
    message += "\nArguments: ";
    message += server.args();
    message += "\n";
    for (uint8_t i=0; i<server.args(); i++){
       message += " " + server.argName(i) + ": " + server.arg(i) + "\n";
    }
    server.send(404, "text/plain", message);
    MyDbg(message, true);
 }
void MyWebServer::handleRoot () static
Redirect a root call to the Main.html site.
Definition at line 324 of file WebServer.h.
References server.
Referenced by begin().
 {
    server.sendHeader("Location", "Main.html", true);
    server.send(302, "text/plain", "");
 }
void MyWebServer::handleSaveSettings () static
Reads all the options from the url and save them to the SPIFFS.
Definition at line 471 of file WebServer.h.
References MyOptions::bme280CheckIntervalSec, MyOptions::deepSleepTimeSec, GetOption(), MyOptions::gprsAP, MyOptions::gpsCheckIntervalSec, MyOptions::isDebugActive, MyOptions::isDeepSleepEnabled, MyOptions::isGpsEnabled, MyOptions::isGsmEnabled, MyOptions::isMqttEnabled, loadMain(), loadRestart(), MyOptions::mqttName, MyOptions::mqttPassword, MyOptions::mqttPort, MyOptions::mqttReconnectIntervalSec, MyOptions::mqttSendOnMoveEverySec, MyOptions::mqttSendOnNonMoveEverySec, MyOptions::mqttServer, MyOptions::mqttUser, myData, MyDbg(), myOptions, MyOptions::phoneNumber, MyOptions::powerCheckIntervalSec, MyOptions::powerSaveModeVoltage, MyData::restartInfo, MyOptions::save(), MyOptions::smsCheckIntervalSec, MyOptions::wakeTimeSec, MyOptions::wlanAP, and MyOptions::wlanPassword.
Referenced by begin().
 {
    if (!myOptions || !myData) {
       return;
    }
    MyDbg("SaveSettings", true);
    GetOption("gprsAP",                    myOptions->gprsAP);
    GetOption("wlanAP",                    myOptions->wlanAP);
    GetOption("wlanPassword",              myOptions->wlanPassword);
    GetOption("isDebugActive",             myOptions->isDebugActive);
    GetOption("bme280CheckIntervalSec",    myOptions->bme280CheckIntervalSec);
    GetOption("isGsmEnabled",              myOptions->isGsmEnabled);
    GetOption("phoneNumber",               myOptions->phoneNumber);
    GetOption("smsCheckIntervalSec",       myOptions->smsCheckIntervalSec);
    GetOption("isGpsEnabled",              myOptions->isGpsEnabled);
    GetOption("gpsCheckIntervalSec",       myOptions->gpsCheckIntervalSec);
    GetOption("isDeepSleepEnabled",        myOptions->isDeepSleepEnabled);
    GetOption("powerSaveModeVoltage",      myOptions->powerSaveModeVoltage);
    GetOption("powerCheckIntervalSec",     myOptions->powerCheckIntervalSec);
    GetOption("wakeTimeSec",               myOptions->wakeTimeSec);
    GetOption("deepSleepTimeSec",          myOptions->deepSleepTimeSec);
    GetOption("isMqttEnabled",             myOptions->isMqttEnabled);
    GetOption("mqttName",                  myOptions->mqttName);
    GetOption("mqttServer",                myOptions->mqttServer);
    GetOption("mqttPort",                  myOptions->mqttPort);
    GetOption("mqttUser",                  myOptions->mqttUser);
    GetOption("mqttPassword",              myOptions->mqttPassword);
    GetOption("mqttReconnectIntervalSec",  myOptions->mqttReconnectIntervalSec);
    GetOption("mqttSendOnMoveEverySec",    myOptions->mqttSendOnMoveEverySec);
    GetOption("mqttSendOnNonMoveEverySec", myOptions->mqttSendOnNonMoveEverySec);
    myOptions->save();
    if (false /* reboot */) {
       myData->restartInfo =
          "<b>Settings saved</b>";
       loadRestart();
    }
    loadMain();
 }
void MyWebServer::handleWebRequests () static
Default for an unknown web request on not found.
Definition at line 670 of file WebServer.h.
References handleNotFound(), loadFromSpiffs(), and server.
Referenced by begin().
 {
    if (loadFromSpiffs(server.uri())) {
       return;
    }
    handleNotFound();
 }
void MyWebServer::loadConsole () static
Load the console page
Definition at line 580 of file WebServer.h.
References handleNotFound(), loadFromSpiffs(), MyData::logInfos, myData, StringList::removeAll(), and server.
Referenced by begin().
 {
    if (loadFromSpiffs("/Console.html")) {
       if (server.hasArg("clear")) {
          myData->logInfos.removeAll();
       }
       return;
    }
    handleNotFound();
 }
void MyWebServer::loadFirmwareUpdate () static
Load the FirmwareUpdate page after starting OTA.
Definition at line 389 of file WebServer.h.
References handleNotFound(), MyData::isOtaActive, loadFromSpiffs(), myData, myOptions, and SetupOTA().
Referenced by begin().
 {
    if (!myOptions || !myData) {
       return;
    }
    if (!myData->isOtaActive) {
       SetupOTA();
       ArduinoOTA.begin();
       myData->isOtaActive = true;
    }
    if (loadFromSpiffs("/FirmwareUpdate.html")) {
       return;
    }
    handleNotFound();
 }
bool MyWebServer::loadFromSpiffs (String path) static protected
Helper function to load a file from the SPIFFS.
Definition at line 290 of file WebServer.h.
References server.
Referenced by handleWebRequests(), loadConsole(), loadFirmwareUpdate(), loadMain(), loadRestart(), and loadSettings().
 {
    bool ret = false;
    String dataType = "text/plain";
    if(path.endsWith("/")) path += "index.htm";
    if(path.endsWith(".src")) path = path.substring(0, path.lastIndexOf("."));
    else if(path.endsWith(".html")) dataType = "text/html";
    else if(path.endsWith(".htm")) dataType = "text/html";
    else if(path.endsWith(".css")) dataType = "text/css";
    else if(path.endsWith(".js")) dataType = "application/javascript";
    else if(path.endsWith(".png")) dataType = "image/png";
    else if(path.endsWith(".gif")) dataType = "image/gif";
    else if(path.endsWith(".jpg")) dataType = "image/jpeg";
    else if(path.endsWith(".ico")) dataType = "image/x-icon";
    else if(path.endsWith(".xml")) dataType = "text/xml";
    else if(path.endsWith(".pdf")) dataType = "application/pdf";
    else if(path.endsWith(".zip")) dataType = "application/zip";
    File dataFile = SPIFFS.open(path.c_str(), "r");
    if (dataFile) {
       if (server.hasArg("download")) {
          dataType = "application/octet-stream";
       }
       if (server.streamFile(dataFile, dataType) == dataFile.size()) {
          ret = true;
       }
       dataFile.close();
    }
    return ret;
 }
void MyWebServer::loadMain () static
Sends the Main.html to the client.
Definition at line 331 of file WebServer.h.
References handleNotFound(), and loadFromSpiffs().
Referenced by begin(), and handleSaveSettings().
 {
    if (loadFromSpiffs("/Main.html")) {
       return;
    }
    handleNotFound();
 }
void MyWebServer::loadRestart () static
Load the restart page.
Definition at line 623 of file WebServer.h.
References handleNotFound(), loadFromSpiffs(), MyDbg(), and myDelay().
Referenced by begin(), and handleSaveSettings().
 {
    if (loadFromSpiffs("/Restart.html")) {
       MyDbg("Load File /Restart.html", true);
       myDelay(2000);
       MyDbg("Restart", true);
       ESP.restart();
       return;
    }
    handleNotFound();
 }
void MyWebServer::loadSettings () static
Load the Settings page.
Definition at line 407 of file WebServer.h.
References handleNotFound(), and loadFromSpiffs().
Referenced by begin().
 {
    if (loadFromSpiffs("/Settings.html")) {
       return;
    }
    handleNotFound();
 }
String MyWebServer::TextToXml (String data) static protected
Helper HTML text conversation function for special character.
Definition at line 173 of file WebServer.h.
Referenced by AddOption(), AddTableTr(), and handleLoadConsoleInfo().
 {
    data.replace(F("&"), F("%26"));
    data.replace(F("<"), F("%3C"));
    data.replace(F(">"), F("%3E"));
    return data;
 }
The documentation for this class was generated from the following file:
tracker/WebServer.h