Snorktracker: MyMqtt Class Reference
MyMqtt Class Reference
#include <Mqtt.h>
Public Member Functions
MyMqtt (MyGsmGps &gsmGps, MyOptions &options, MyData &data)
bool begin ()
void handleClient ()
Static Public Member Functions
static void mqttCallback (char *topic, byte *payload, unsigned int len)
Protected Member Functions
void reconnect ()
bool sendData ()
Protected Attributes
MyGsmGps & myGsmGps
Reference to the Gsmgps instnces.
MyOptions & myOptions
Reference to the options.
MyData & myData
Reference to the data.
long mqttLastSendSec
Timestamp from the last send.
long mqttLastReconnectSec
Timestamp from the last server connection.
long lastGpsPublishedSec
The last timestamp of the sended gps data.
Static Protected Attributes
static MyOptions * g_myOptions = NULL
Static option pointer for the callback function.
Detailed Description
MQTT client for sending the collected data to a MQTT server
Definition at line 55 of file Mqtt.h.
Constructor & Destructor Documentation
MyMqtt::MyMqtt (MyGsmGps & gsmGps, MyOptions & options, MyData & data)
Constructor/Destructor
Definition at line 90 of file Mqtt.h.
References g_myOptions.
    : myGsmGps(gsmGps)
    , PubSubClient(gsmGps.gsmClient)
    , myOptions(options)
    , myData(data)
    , mqttLastSendSec(0)
    , mqttLastReconnectSec(0)
    , lastGpsPublishedSec(0)
 {
    g_myOptions = &options;
 }
Member Function Documentation
bool MyMqtt::begin ()
Sets the MQTT server settings
Definition at line 161 of file Mqtt.h.
References MQTT_PORT, MQTT_SERVER, mqttCallback(), and MyDbg().
Referenced by setup().
 {
    MyDbg("MQTT:begin");
    setServer(MQTT_SERVER, MQTT_PORT);
    setCallback(mqttCallback);
    return true;
 }
void MyMqtt::handleClient ()
Connect To the MQTT server and send the data when the time is right.
Definition at line 171 of file Mqtt.h.
References MyGsmGps::isGsmActive, MyData::isMoving, mqttLastReconnectSec, mqttLastSendSec, MyOptions::mqttReconnectIntervalSec, MyOptions::mqttSendOnMoveEverySec, MyOptions::mqttSendOnNonMoveEverySec, myData, myGsmGps, myOptions, reconnect(), and sendData().
Referenced by loop().
 {
    if (myGsmGps.isGsmActive) {
       if (!PubSubClient::connected()) {
          long currSec = millis() / 1000;
          if (currSec - mqttLastReconnectSec > myOptions.mqttReconnectIntervalSec) {
             mqttLastReconnectSec = currSec;
             reconnect();
          }
       }
       if (connected()) {
          bool send       = false;
          long currentSec = millis() / 1000;
          if (myData.isMoving) {
             send = currentSec - mqttLastSendSec > myOptions.mqttSendOnMoveEverySec;
          } else {
             send = currentSec - mqttLastSendSec > myOptions.mqttSendOnNonMoveEverySec;
          }
          if (send && sendData()) {
             mqttLastSendSec = currentSec;
          }
       }
    }
 }
void MyMqtt::mqttCallback (char * topic, byte * payload, unsigned int len) static
Static function for MQTT callback on registered topics.
Definition at line 201 of file Mqtt.h.
References g_myOptions, MyOptions::gsmPower, MyOptions::isGpsEnabled, MyOptions::isGsmEnabled, MyOptions::mqttSendOnMoveEverySec, MyOptions::mqttSendOnNonMoveEverySec, MyDbg(), topic_gps_enabled, topic_gsm_enabled, topic_gsm_power, topic_send_on_move_every, and topic_send_on_non_move_every.
Referenced by begin().
 {
    String strTopic = String((char*)topic);
    payload[len] = '\0';
    MyDbg("Message arrived [" + strTopic + "]:[ ");
    if (len) MyDbg((char *) payload);
    MyDbg("]");
    if (MyMqtt::g_myOptions) {
       if (strTopic == topic_gsm_power) {
          g_myOptions->gsmPower = atoi((char *) payload);
          MyDbg(strTopic + g_myOptions->gsmPower ? " - On" : " - Off");
       }
       if (strTopic == topic_gsm_enabled) {
          g_myOptions->isGsmEnabled = atoi((char *) payload);
          MyDbg(strTopic + g_myOptions->isGsmEnabled ? " - Enabled" : " - Disabled");
       }
       if (strTopic == topic_gps_enabled) {
          g_myOptions->isGpsEnabled = atoi((char *) payload);
          MyDbg(strTopic + g_myOptions->isGpsEnabled ? " - Enabled" : " - Disabled");
       }
       if (strTopic == topic_send_on_move_every) {
          g_myOptions->mqttSendOnMoveEverySec = atoi((char *) payload);
          MyDbg(strTopic + " - " + String(g_myOptions->mqttSendOnMoveEverySec));
       }
       if (strTopic == topic_send_on_non_move_every) {
          g_myOptions->mqttSendOnNonMoveEverySec = atoi((char *) payload);
          MyDbg(strTopic + " - " + String(g_myOptions->mqttSendOnNonMoveEverySec));
       }
    }
 }
void MyMqtt::reconnect () protected
Connects or reconnect to the MQTT server and subscribes the topics.
Definition at line 107 of file Mqtt.h.
References MQTT_NAME, MQTT_PASSWORD, MQTT_USER, MyDbg(), myDelay(), topic_cmd, topic_gps_enabled, topic_gsm_enabled, topic_gsm_power, topic_send_on_move_every, and topic_send_on_non_move_every.
Referenced by handleClient().
 {
    MyDbg("Attempting MQTT connection...");
    // Try 5 times to reconnected
    for (int i = 0; !PubSubClient::connected() && i < 5; i++) {
       // Attempt to connect
       if (PubSubClient::connect(MQTT_NAME, MQTT_USER, MQTT_PASSWORD)) {
          subscribe(topic_cmd);
          subscribe(topic_gsm_power);
          subscribe(topic_gsm_enabled);
          subscribe(topic_gps_enabled);
          subscribe(topic_send_on_move_every);
          subscribe(topic_send_on_non_move_every);
          MyDbg(" connected");
       } else {
          MyDbg(" Failed (" + String(i+1) + ") rc =" + String(state()));
          MyDbg(" Try again in 5 seconds");
          // Wait 5 seconds before retrying
          myDelay(5000);
          MyDbg(".", false, false);
       }
    }
 }
bool MyMqtt::sendData () protected
Send the mqtt data if the gps values are new.
Definition at line 132 of file Mqtt.h.
References MyData::altitude, MyData::batteryLevel, MyData::batteryVolt, MyData::humidity, MyData::kmph, lastGpsPublishedSec, MyData::lastGpsUpdateSec, MyData::latitude, MyData::longitude, myData, MyDbg(), MyData::pressure, MyData::signalQuality, MyData::temperature, topic_alt, topic_batt_level, topic_batt_volt, topic_csq, topic_humidity, topic_kmph, topic_lat, topic_lon, topic_pressure, topic_temperature, topic_voltage, and MyData::voltage.
Referenced by handleClient().
 {
    if (myData.lastGpsUpdateSec != lastGpsPublishedSec) {
       MyDbg("Attempting MQTT publishing");
       if (PubSubClient::connected()) {
          publish(topic_voltage, String(myData.voltage).c_str(), true);
          publish(topic_temperature, String(myData.temperature).c_str(), true);
          publish(topic_humidity,    String(myData.humidity).c_str(),    true);
          publish(topic_pressure,    String(myData.pressure).c_str(),    true);
          publish(topic_csq,        myData.signalQuality.c_str(), true);
          publish(topic_batt_level, myData.batteryLevel.c_str(),  true);
          publish(topic_batt_volt,  myData.batteryVolt.c_str(),   true);
          publish(topic_lon,  myData.longitude.c_str(), true);
          publish(topic_lat,  myData.latitude.c_str(),  true);
          publish(topic_alt,  myData.altitude.c_str(),  true);
          publish(topic_kmph, myData.kmph.c_str(),      true);
          lastGpsPublishedSec = myData.lastGpsUpdateSec;
          MyDbg("mqtt published");
          return true;
       }
    }
    return false;
 }
The documentation for this class was generated from the following file:
tracker/Mqtt.h